---
  - name: AWS EC2 Instance
    hosts: localhost
    connection: local
    gather_facts: false
    tasks:
      - name: Create ec2 instance
        ec2:
          instance_type: t2.micro
          image: ami-06ec8443c2a35b0ba
          count: 1
          key_name: ansible
          group: all-allow
          wait: yes
          region: eu-central-1
          instance_tags:
            Name: webserver1
            Env: web
        register: ec2

  # - name: Create SSH Group to login dynamically to EC2 Instance
  #   add_host: 
  #     hostname: "{{ item.public_ip }}"
  #     ansible_ssh_private_key_file: path/to/test-pair.pem
  #     groupname: ec2_server
  #   with_items: ec2.instances

  # - name: Add new instance to host group
  #   add_host:
  #     hostname: "{{ item.public_ip }}"   
  #     ansible_host: "{{ item.public_ip }}"   
  #     groups: webserver  #Group name where instance will belong
  #     ansible_ssh_private_key_file: '/home/osboxes/.ssh/ansible.pem'
  #     ansible_ssh_user: ec2-user   #User name that will be used while connecting
  #   loop: "{{ ec2.instances }}"   #Loop to add all the newly created instances

#  - name: WEB AWS EC2 Instance
#    hosts: localhost
#    connection: local
#    gather_facts: false
#    tasks:
#      - name: Create ec2 instance
#        ec2:
#          instance_type: t2.micro
#          image: ami-06ec8443c2a35b0ba
#          count: 1
#          key_name: ansible
#          group: all-allow
#          wait: yes
#          region: eu-central-1         
#          instance_tags:
#            Name: webserver2
#            Env: web
#        register: ec2

# - name: Add new instance to host group
#   add_host:
#     hostname: "{{ item.public_ip }}"   
#     ansible_host: "{{ item.public_ip }}"   
#     groups: webserver  #Group name where instance will belong
#     ansible_ssh_private_key_file: '/home/osboxes/.ssh/ansible.pem'
#     ansible_ssh_user: ec2-user   #User name that will be used while connecting
#   loop: "{{ ec2.instances }}"   #Loop to add all the newly created instances

#  - name: DB AWS EC2 Instance
#    hosts: localhost
#    connection: local
#    gather_facts: false
#    tasks:
#      - name: Create ec2 DB instance
#        ec2:
#          instance_type: t2.micro
#          image: ami-06ec8443c2a35b0ba
#          count: 1
#          key_name: ansible
#          group: all-allow
#          wait: yes
#          region: eu-central-1
#          instance_tags:
#            Name: dbserver1
#            Env: db
#        register: ec2

# - name: Add new instance to host group
#   add_host:
#     hostname: "{{ item.public_ip }}"   
#     ansible_host: "{{ item.public_ip }}"   
#     groups: dbserver  #Group name where instance will belong
#     ansible_ssh_private_key_file: '/home/osboxes/.ssh/ansible.pem'
#     ansible_ssh_user: ec2-user   #User name that will be used while connecting
#   loop: "{{ ec2.instances }}"   #Loop to add all the newly created instances
