---
 - name: Working with AWS EC2 Instance
   hosts: localhost
   connection: local
   gather_facts: false
   tasks:
     - name: Create ec2 instance
       ec2:
         instance_type: t2.micro
         image: ami-06ec8443c2a35b0ba
         count: 3
         key_name: ansible
         group: all-allow
         wait: yes
         region: eu-central-1
         instance_tags:
           Env: db_and_web
