---
 - name: WEB AWS EC2 Instance
   hosts: localhost
   connection: local
   gather_facts: false
   tasks:
     - name: Create ec2 instance
       ec2:
         instance_type: t2.micro
         image: ami-06ec8443c2a35b0ba
         count: 1
         key_name: ansible
         group: all-allow
         wait: yes
         region: eu-central-1
         instance_tags:
           Name: webserver1
           Env: web

 - name: WEB AWS EC2 Instance
   hosts: localhost
   connection: local
   gather_facts: false
   tasks:
     - name: Create ec2 instance
       ec2:
         instance_type: t2.micro
         image: ami-06ec8443c2a35b0ba
         count: 1
         key_name: ansible
         group: all-allow
         wait: yes
         region: eu-central-1         
         instance_tags:
           Name: webserver2
           Env: web

 - name: DB AWS EC2 Instance
   hosts: localhost
   connection: local
   gather_facts: false
   tasks:
     - name: Create ec2 DB instance
       ec2:
         instance_type: t2.micro
         image: ami-06ec8443c2a35b0ba
         count: 1
         key_name: ansible
         group: all-allow
         wait: yes
         region: eu-central-1
         instance_tags:
           Name: dbserver1
           Env: web

- name: Add web servers to inventory
  add_host:
    name: '{{ ip_from_ec2 }}'
    hostname: '{{ item.public_ip }}'
    privateip: '{{ item.private_ip }}'
    groups: web_servers
    foo: 42
