---

- name: Deploy dependency
  hosts: awswebserver
  gather_facts: false
  roles:
    - {role: db_web_server, tags: ['python'],   db_web_server: python }
    - {role: db_web_server, tags: ['web'],      db_web_server: flask_web }

