---

- name: Deploy dependency
  hosts: webserver,dbserver
  roles:
    - python

- name: Deploy web
  hosts: webserver,dbserver
  roles:
    - flask_web

- name: Deploy db
  hosts: webserver,dbserver
  roles:
    - sql_server
