---
- name: AWS EC2 Instance
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:

    - name: Display result
      debug:
        msg:
          - instance_list: "{{ instance_list }}"
          - image: "{{ image }}"
          - ansible_ssh_private_key_file: "{{ ansible_ssh_private_key_file }}"
          - ansible_ssh_user: "{{ ansible_ssh_user }}"
  
    # - name: Create ec2 instance
    #   ec2:
    #     instance_type: "{{ instance_type }}"
    #     image: "{{ image }}"
    #     exact_count: 1
    #     count_tag:
    #       Name: "{{ item }}"
    #     key_name: ansible
    #     group: all-allow
    #     wait: true
    #     region: eu-central-1
    #     instance_tags:
    #       Name: "{{ item }}"
    #       Env: web
    #   register: ec2
    #   with_items: "{{ instance_list }}"

    # - name: Add new instance to host group
    #   add_host:
    #     hostname: "{{ item.public_ip }}"
    #     ansible_host: "{{ item.public_ip }}"
    #     groups: awswebserver
    #     ansible_ssh_private_key_file: "{{ ansible_ssh_private_key_file }}"
    #     ansible_ssh_user: "{{ ansible_ssh_user }}"
    #   loop: "{{ ec2.tagged_instances }}"

    # - name: Display result
    #   debug:
    #     msg:
    #       - "{{ groups }}"

    # - name: Wait for SSH to come up
    #   wait_for:
    #     host: "{{ item.public_ip }}"
    #     port: 22
    #     state: started
    #   with_items: "{{ ec2.tagged_instances }}"

    # - name: Create ec2 instance
    #   ec2:
    #     instance_type: t2.micro
    #     image: ami-06ec8443c2a35b0ba
    #     exact_count: 1
    #     count_tag:
    #       Name: "web_server_2"
    #     key_name: ansible
    #     group: all-allow
    #     wait: true
    #     region: eu-central-1
    #     instance_tags:
    #       Name: "web_server_2"
    #       Env: web
    #   register: ec2

    # - name: Add new instance to host group
    #   add_host:
    #     hostname: "{{ item.public_ip }}"
    #     ansible_host: "{{ item.public_ip }}"
    #     groups: awswebserver
    #     ansible_ssh_private_key_file: '/home/osboxes/.ssh/ansible.pem'
    #     ansible_ssh_user: ec2-user
    #   loop: "{{ ec2.tagged_instances }}"

    # - name: Display result
    #   debug:
    #     msg:
    #       - "{{ groups }}"

    # - name: Wait for SSH to come up
    #   wait_for:
    #     host: "{{ item.public_ip }}"
    #     port: 22
    #     state: started
    #   with_items: "{{ ec2.tagged_instances }}"

    # # - name: Display result
    # #   debug:
    # #     msg: 
    # #       - "{{ groups }}"
    # #       - "{{ result }}"

    # - name: Create ec2 DB instance
    #   ec2:
    #     instance_type: t2.micro
    #     image: ami-06ec8443c2a35b0ba
    #     exact_count: 1
    #     count_tag:
    #       Name: "db_server_1"
    #     key_name: ansible
    #     group: all-allow
    #     wait: true
    #     region: eu-central-1
    #     instance_tags:
    #       Name: "db_server_1"
    #       Env: db
    #   register: ec2

    # - name: Add new instance to host group
    #   add_host:
    #     hostname: "{{ item.public_ip }}"
    #     ansible_host: "{{ item.public_ip }}"
    #     groups: awsdbserver
    #     ansible_ssh_private_key_file: '/home/osboxes/.ssh/ansible.pem'
    #     ansible_ssh_user: ec2-user
    #   loop: "{{ ec2.tagged_instances }}"

    # # - name: Display result
    # #   debug:
    # #     msg:
    # #       - "{{ groups }}"

    # - name: Wait for SSH to come up
    #   wait_for:
    #     host: "{{ item.public_ip }}"
    #     port: 22
    #     state: started
    #   with_items: "{{ ec2.tagged_instances }}"