  - name:  Install all required dependencies
    become: Yes
    become_method: sudo
    become_user: root
    yum: 
      name: 
      - python3-pip
      - python3-wheel
      - python3-devel
      - "@Development tools"
      state: installed