- name: InstallpythonFlaskdependency
  become: true
  become_method: sudo
  become_user: root
  pip:
    name:
      - Flask
      - Flask-MySQL
      - PyMySQL
    state: present
    extra_args: -q

- name: Example clone of a single branch
  become: true
  become_method: sudo
  become_user: root
  ansible.builtin.git:
    repo: https://github.com/mmumshad/simple-webapp.git
    dest: /opt/application
    version: master

# - name: Open-ports 5000
#   become: true
#   become_method: sudo
#   become_user: root
#   shell: firewall-cmd --zone=public --permanent --add-port 5000/tcp >> log1.txt

# - name: Open-ports 5000
#   become: true
#   become_method: sudo
#   become_user: root
#   shell: firewall-cmd --reload >> log2.txt

- name: Start->web server
  shell: FLASK_APP=/opt/application/app.py nohup flask run --host=0.0.0.0 &
