- name: Install all required dependencies
  become: true
  become_method: sudo
  become_user: root
  yum:
    name:
      - python3-pip
      - python3-wheel
      - python3-devel
      - "@Development tools"
    state: installed

- name: Install Python Flask Dependency
  become: true
  become_method: sudo
  become_user: root
  pip:
    name:
      - PyMySQL
    state: present
    extra_args: -q
